//chatGPT generated skills
List<String> computerRelatedSkills = [
    "Java", "Python", "JavaScript", "C/C++", "Ruby", "PHP", "Swift", "Kotlin", "C#", "TypeScript", "SQL", "HTML/CSS", "R", "MATLAB",
    "Frontend Development", "Backend Development", "Full Stack Development", "Responsive Web Design", "Web Frameworks (e.g., React, Angular, Vue.js)", "RESTful APIs", "Web Security",
    "iOS Development (Swift, Objective-C)", "Android Development (Java, Kotlin)", "Cross-platform Development (React Native, Flutter)",
    "SQL (MySQL, PostgreSQL, SQLite, SQL Server)", "NoSQL (MongoDB, Cassandra, Redis)",
    "Windows", "macOS", "Linux/Unix",
    "Continuous Integration/Continuous Deployment (CI/CD)", "Version Control (Git, SVN)", "Containerization (Docker, Kubernetes)", "Infrastructure as Code (Terraform, CloudFormation)", "Configuration Management (Ansible, Chef, Puppet)",
    "Amazon Web Services (AWS)", "Microsoft Azure", "Google Cloud Platform (GCP)", "Serverless Computing",
    "TCP/IP", "LAN/WAN", "Routing and Switching", "Network Security", "VPNs",
    "Ethical Hacking", "Penetration Testing", "Threat Analysis", "Cryptography", "Security Compliance (e.g., GDPR, HIPAA)",
    "Data Visualization (Tableau, Power BI)", "Machine Learning (Scikit-learn, TensorFlow, PyTorch)", "Big Data Technologies (Hadoop, Spark)", "Statistical Analysis (R, Python)",
    "Agile Methodologies", "Software Development Life Cycle (SDLC)", "Object-Oriented Programming (OOP)", "Design Patterns", "Test-Driven Development (TDD)",
    "User Interface Design", "User Experience Design", "Prototyping Tools (Sketch, Adobe XD, Figma)", "Usability Testing",
    "Virtualization (VMware, VirtualBox)", "Scripting (Bash, PowerShell)", "GitOps", "Natural Language Processing (NLP)", "Quantum Computing"
];
//generated from chatGPT
const citiesInIndia = [
    "Mumbai",
    "Delhi",
    "Bangalore",
    "Hyderabad",
    "Ahmedabad",
    "Chennai",
    "Kolkata",
    "Surat",
    "Pune",
    "Jaipur",
    "Lucknow",
    "Kanpur",
    "Nagpur",
    "Indore",
    "Thane",
    "Bhopal",
    "Visakhapatnam",
    "Pimpri-Chinchwad",
    "Patna",
    "Vadodara",
    "Ghaziabad",
    "Ludhiana",
    "Agra",
    "Nashik",
    "Faridabad",
    "Meerut",
    "Rajkot",
    "Kalyan-Dombivali",
    "Vasai-Virar",
    "Varanasi",
    "Srinagar",
    "Aurangabad",
    "Dhanbad",
    "Amritsar",
    "Navi Mumbai",
    "Allahabad",
    "Ranchi",
    "Howrah",
    "Jabalpur",
    "Gwalior",
    "Vijayawada",
    "Jodhpur",
    "Madurai",
    "Raipur",
    "Kota",
    "Guwahati",
    "Chandigarh",
    "Solapur",
    "Hubli-Dharwad",
    "Bareilly",
    "Moradabad",
    "Mysore",
    "Gurgaon",
    "Aligarh",
    "Jalandhar",
    "Tiruchirappalli",
    "Bhubaneswar",
    "Salem",
    "Warangal",
    "Guntur",
    "Bhiwandi",
    "Saharanpur",
    "Gorakhpur",
    "Bikaner",
    "Amravati",
    "Noida",
    "Jamshedpur",
    "Bhilai",
    "Cuttack",
    "Firozabad",
    "Kochi",
    "Nellore",
    "Bhavnagar",
    "Dehradun",
    "Durgapur",
    "Asansol",
    "Rourkela",
    "Nanded",
    "Kolhapur",
    "Ajmer",
    "Akola",
    "Gulbarga",
    "Jamnagar",
    "Ujjain",
    "Loni",
    "Siliguri",
    "Jhansi",
    "Ulhasnagar",
    "Jammu",
    "Sangli-Miraj & Kupwad",
    "Mangalore",
    "Erode",
    "Belgaum",
    "Ambattur",
    "Tirunelveli",
    "Malegaon",
    "Gaya",
    "Jalgaon",
    "Udaipur",
    "Maheshtala",
    "Davanagere",
    "Kozhikode",
    "Kurnool",
    "Rajpur Sonarpur",
    "Rajahmundry",
    "Bokaro Steel City",
    "South Dumdum",
    "Bellary",
    "Patiala",
    "Gopalpur",
    "Agartala",
    "Bhagalpur",
    "Muzaffarnagar",
    "Bhatpara",
    "Panihati",
    "Latur",
    "Dhule",
    "Tirupati",
    "Rohtak",
    "Korba",
    "Bhilwara",
    "Berhampur",
    "Muzaffarpur",
    "Ahmednagar",
    "Mathura",
    "Kollam",
    "Avadi",
    "Kadapa",
    "Kamarhati",
    "Sambalpur",
    "Bilaspur",
    "Shahjahanpur",
    "Satara",
    "Bijapur",
    "Rampur",
    "Shivamogga (Shimoga)",
    "Chandrapur",
    "Junagadh",
    "Thrissur",
    "Alwar",
    "Bardhaman",
    "Kulti",
    "Nizamabad",
    "Parbhani",
    "Tumkur",
    "Khammam",
    "Ozhukarai",
    "Bihar Sharif",
    "Panipat",
    "Darbhanga",
    "Bally",
    "Aizawl",
    "Dewas",
    "Ichalkaranji",
    "Karnal",
    "Bathinda",
    "Jalna",
    "Eluru",
    "Barasat",
    "Kirari Suleman Nagar",
    "Purnia",
    "Satna",
    "Mau",
    "Sonipat",
    "Farrukhabad",
    "Sagar",
    "Rourkela Civil Township",
    "Durg",
    "Imphal",
    "Ratlam",
    "Hapur",
    "Arrah",
    "Anantapur",
    "Karimnagar",
    "Etawah",
    "Ambarnath",
    "North Dumdum",
    "Bharatpur",
    "Begusarai",
    "New Delhi",
    "Gandhidham",
    "Baranagar",
    "Tiruvottiyur",
    "Pondicherry",
    "Sikar",
    "Thoothukudi",
    "Rewa",
    "Mirzapur",
    "Raichur",
    "Pali",
    "Ramagundam",
    "Silchar",
    "Vizianagaram",
    "Katihar",
    "Haridwar",
    "Sri Ganganagar",
    "Karawal Nagar",
    "Nagercoil",
    "Mango",
    "Thanjavur",
    "Bulandshahr",
    "Uluberia",
    "Katni",
    "Sambhal",
    "Singrauli",
    "Nadiad",
    "Secunderabad",
    "Naihati",
    "Yamunanagar",
    "Bidhan Nagar",
    "Pallavaram",
    "Bidar",
    "Munger",
    "Panchkula",
    "Burhanpur",
    "Raurkela Industrial Township",
    "Kharagpur",
    "Dindigul",
    "Gandhinagar",
    "Hospet",
    "Nangloi Jat",
    "Malda",
    "Ongole",
    "Deoghar",
    "Chapra",
    "Haldia",
    "Khandwa",
    "Nandyal",
    "Morena",
    "Amroha",
    "Anand",
    "Bhind",
    "Bhalswa Jahangir Pur",
    "Madhyamgram",
    "Bhiwani",
    "Berhampore",
    "Ambala",
    "Morbi",
];